frontend/routes/package/(_components)/PackageHeader.tsx
If the score is 100%, the size is slightly bigger than other scores.
The layout was a little broken, so I fixed it.
=> fix: 100% score is slightly bigger than others

frontend/components/Table.tsx, frontend/routes/@[scope]/(_islands)/ScopeInviteForm.tsx, frontend/routes/@[scope]/(_islands)/ScopeMemberRole.tsx, frontend/routes/@[scope]/~/members.tsx
- updates the scopes members page to use the jsr color palette 
- places warning text before the action you are being warned about
=> fix: update scopes members page styles

frontend/static/styles.css
Some code blocks in package docs are slightly overflowing. This fixes that, and also adds a branded color to scrollbars on some browsers/systems (mostly so that items like these code blocks, which are supposed to go to the edge of the page, go visibly to the edge of the scrollbar instead).
=> Fix horizontal overflow for code blocks and add scrollbar colors

terraform/https.tf, tools/server.ts
=> fix: don't hit API server for /api prefixed paths

frontend/docs/publishing-packages.md
It's `include` and `exclude` instead of `includes` and `excludes`
=> docs: correct include & exclude option

frontend/islands/GithubUserLink.tsx
I stumbled across a typo for GitHub.
=> fix: typo; Github --> GitHub

api/src/reserved_scopes.json
I'm one of The ASF Members. Perhaps I'd start a discussion in the foundation to register a foundation-wise scope and publish Apache projects to JSR.
This file seems to reserve some well-known names to avoid branding issues. I suggest to add "apache" on the list.
=> chore: reserve apache scope for the ASF

api/src/util.rs
Previously when a public request cached the response, even signed in users would be served this response. Now the vary header ensures that only public users will receive the cached response.
=> fix: add vary header to cached responses

api/src/analysis.rs, api/src/npm/mod.rs, api/src/npm/tarball.rs
We previously only transpiled ts sources, but we need to transpile js sources as well to be able to rewrite imports like turning `import ... from "npm:lit@^2.2.7"` into `import ... from "lit";`.
Fixes https://github.com/jsr-io/jsr/issues/139
=> fix: rewrite js import sources

frontend/islands/PackageSearch.tsx
The `pointer-events-auto` was one element too low in the tree.
=> fix: allow clicking on search results again

frontend/docs/faq.md
=> docs: add faq on "Act on your behalf"

api/src/api/package.rs, frontend/routes/package/source.tsx
This page previously was a 404 for the HTML view, but a 200 when `curl`ing.
http://jsr.test/@std/expect/meta.json
=> fix: rendered view of meta.json file

api/src/tarball.rs
=> fix: better error when config file is missing in publishing

frontend/deno.json, frontend/tailwind.config.ts
Tailwindcss applies `height: auto` for img and video tags by default in its preflight.css, so imgs and videos with a height attribute, the most common practice to resize media in markdown, are broken because height property in CSS has a higher priority than the attribute on the DOM.
This PR reimplements the preflight core plugin for tailwindcss and modifies the preflight.css to address this issue.
fixes #120
=> fix: respect img height in docs

frontend/static/styles.css
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Test link: <https://jsr.io/@oak/oak/14.2.0/deno.json>
The `flex` of the code block is overridden by the `display: block` in `.ddoc .markdown pre>code:first-child`. 
[The html in the code block section comes from outside](https://github.com/jsr-io/jsr/blob/acb39921e96fb2b436d352650a1f7675d0982e98/frontend/routes/package/source.tsx#L117-L124) and it is not suitable to change `flex` to `!flex`. So choose `style.css` to add styles to override the `.ddoc .markdown pre>code:first-child` default.
=> fix(frontend): code block style of file

api/.sqlx/query-75a9fca2cd2d0327c9e402315ae81d63b606376548adbd6f98b81f9e09163f50.json, api/migrations/20240305163250_github_id_unique.sql, api/src/auth.rs, api/src/db/database.rs
Previously we'd only sync name and email from GitHub on signup. We now do this in both signup, and signin.
Fixes #173
=> fix: update name and email from GitHub every sign-in

frontend/routes/_layout.tsx, frontend/routes/package/(_components)/Docs.tsx, frontend/routes/package/doc/[file].tsx, frontend/routes/package/doc/[symbol].tsx, frontend/routes/package/index.tsx, frontend/static/styles.css
Fixes https://github.com/jsr-io/jsr/issues/41
Since the layout is designed in a way that the viewport always scrolls (even when the page content is smaller) as it has full width top elements with a sticky sidebar and a large whitespace before the footer (with `class="mb-20"`) on every page, it made sense to make sidebar scrollable independently.
If we don't want viewport to scroll when the page content is smaller, we might want to revisit the layout. (I really like the approach of https://docs.rs on this) But for now independent scrolling should be sufficient imo.
=> fix(frontend): made sidebar on package page scroll independently

api/src/api.yml
=> feat: add github repo to api documentation

frontend/routes/docs/[...id].tsx, frontend/routes/package/score.tsx
Resolves #244.
...and renamed a misnamed component.
Left titles as they are since short, _positive_ sentences make more sense with the progress indicator and the checkmarks imo.
=> docs: improved score description consistency

frontend/docs/troubleshooting.md
I just ran into the `actorNotAuthorized` error and noticed it's not listed on the Troubleshooting page, so I added it.
=> docs: Update troubleshooting.md with actorNotAuthorized

frontend/docs/faq.md, frontend/docs/packages.md, frontend/islands/GlobalSearch.tsx, frontend/routes/packages.tsx
You can now put `runtime:` and `scope:` in the search box to filter searching to a certain runtime or scope.
=> feat: basic filtering for runtime & scope

frontend/docs/native-imports.md
I found that the anchor tag seems to be updated in the past. Therefore the anchor is not working as expected. This PR should fix it
=> docs(native-imports): updated anchor tag in native imports

api/src/reserved_scopes.json
Hi, we (@yasunori, @Omochice, @ryoppippi, @take and myself) propose the `example` namespace, which guarantees that there are no modules at all. This is intended to be a safe namespace for sample code, etc.
We would like to update the doc if this is accepted. Would you mind telling me which repository to update for this namespace?
=> Add 'example' namespace as reserved one.

frontend/routes/badges/package.ts, frontend/routes/badges/package_score.ts
This is a style proposal related to https://github.com/simple-icons/simple-icons/pull/10794#discussion_r1559656261. It has a better visual on the logo and its stroke.
=> chore: adjust badge colors

frontend/components/ListPanel.tsx
Fixed it by setting a max width on the version and truncating both names and the versions.
=> fix(UI/UX): long package names disrupting the box layout

frontend/components/Header.tsx, frontend/fresh.gen.ts, frontend/islands/HeaderLogo.tsx
I noticed this little spinny effect was broken so I reintroduced it in a new way. I don't now if it's a good idea or a good implementation of the idea, but it's kinda fun. ¯\\\_(ツ)_/¯
=> Fix spinning logo in header. (Good idea? ¯\_(ツ)_/¯)

api/Cargo.lock, api/Cargo.toml, api/src/analysis.rs, api/src/api/admin.rs, api/src/api/package.rs, api/src/db/models.rs, api/src/main.rs, api/src/npm/tarball.rs, api/src/npm/tests.rs, api/src/publish.rs, api/src/tarball.rs, api/src/tasks.rs, api/src/util.rs, api/testdata/specs/npm_tarballs/import_jsr.txt
This cleans up a lot of code because we do not have to ensure during graph building that all JSR dependencies resolve correctly.
This is also a fix for the stuck npm tarball rebuilds that are caused by users making semver incompatible changes to their `exports` maps.
=> refactor: use `passthrough_jsr_specifier` deno_graph option

frontend/docs/faq.md
It's best practice to not skip heading levels in the hierarchy.
=> docs: fix heading hierarchy in FAQ page

api/src/analysis.rs, api/src/publish.rs, api/src/tarball.rs, api/testdata/tarballs/triple_slash_reference_in_jsdoc/jsr.json, api/testdata/tarballs/triple_slash_reference_in_jsdoc/mod.ts
=> fix: don't ban triple slash references inside of jsdoc comments

frontend/components/HomepageHero.tsx
Set pointer-events to none for the HomepageHero canvas so that text can be selected.
=> Set pointer-events-auto class on HomepageHero text

frontend/components/RuntimeCompatIndicator.tsx, frontend/routes/package/(_components)/PackageHeader.tsx, frontend/static/styles.css
A few random alignment things I noticed while playing around with package header to make the spacing between elements the same whether it's an image or text in the package header.
I also updated the nav links with the new underline style we're planning to use for the new breadcrumbs as I think it makes sense to use that style there as well as they serve a similar role (links as UI navigation rather than in-text links)
=> fix: header alignment refinement + nav link style

frontend/islands/UserMenu.tsx
Some small style updates to account for the fact that we use a yellow button in our user menu and hover states are also yellow and that made it hard to distinguish what you were highlighting
Also made some minor profile pic/name spacing updates that felt more size-appropriate given the size of the menu box
Normal
Hover state
Focus state (using tab to select)
=> fix: style updates to user menu

frontend/routes/package/score.tsx, frontend/routes/package/settings.tsx
This PR adds links to the settings page in the score page.
Closes #423 
Before:
After(with admin role): 
After(without admin role):
=> fix(frontend): add links to the settings page in the score page

frontend/components/Header.tsx, frontend/routes/package/(_components)/PackageHeader.tsx
two small style fixes I missed on a recent PR. The text on Published was not right aligned and the sign in button didn't get the same link styles as the other link.
=> fix: right alignment on publish and signed out link style

terraform/https.tf
=> fix: don't allow tls versions older than TLS 1.2

api/.sqlx/query-4d1bd2eec86b947f3af850587ba6b1c1e95f030a6e9384b1c3ec510c04ec72d9.json, api/.sqlx/query-5201b8729ba43beca8c9749e6d797c83a4c323d0a3e2720ceedac9cea7010ec9.json, api/migrations/20240422122600_personal_access_token.sql, api/src/npm/mod.rs, api/src/npm/specifiers.rs, api/src/npm/tarball.rs, api/testdata/specs/npm_tarballs/slow_types_transpile.txt
This was happening for packages that had slow types.
Fixes #446
=> fix: don't reference .ts source in package.json types

Cargo.lock, api/Cargo.toml, api/src/ids.rs, api/src/npm/emit.rs, api/src/npm/mod.rs, api/src/npm/specifiers.rs, api/src/npm/tarball.rs, api/testdata/specs/npm_tarballs/additional_files.txt, api/testdata/specs/npm_tarballs/import_jsr.txt, api/testdata/specs/npm_tarballs/import_npm.txt, api/testdata/specs/npm_tarballs/js_with_dts.txt, api/testdata/specs/npm_tarballs/jsdoc_import.txt, api/testdata/specs/npm_tarballs/slow_types_transpile.txt, api/testdata/specs/npm_tarballs/transpile.txt, api/testdata/specs/npm_tarballs/transpile_with_imports.txt, api/testdata/specs/npm_tarballs/type_imports.txt, frontend/docs/troubleshooting.md, frontend/fresh.gen.ts
Fixes #462 
To make this work, also bans publishing packages containing a top level folder called `_dist`.
Also we now do not reference `.d.ts` files from other `.d.ts` files using the `.d.ts` extension, because otherwise tsc gets upset. So we instead use `.js` (even if the file does not exist!)
Also we emit source maps into separate files, because TSC doesn't understand embedded source maps.
=> fix: emit .d.ts and .js files into _dist folder and other fixes

frontend/fresh.gen.ts, frontend/routes/package/(_components)/Docs.tsx, frontend/static/styles.css
Quite a long list of style changes affecting the Docs tab. I did them all in the jsr repo instead of ddoc because it was an easier dev workflow but it may be better to use this as a reference for what needs to change in deno_doc with the goal of eliminating nearly every `body .ddoc` style out of the stylesheet with the exception of any jsr theme colors. 
If we want to review and merge this we can but if we want to leave it as a TODO list and then close it out when deno_doc gets the updates, that's fine too. 
also fixes #451
=> fix: design update to Docs tab

frontend/routes/badges/package.ts, frontend/routes/badges/package_score.ts, frontend/routes/badges/scope.ts
Fixes #341
I used the same value `300` as shields.io's npm version badge.
=> fix: specify the cache-control for badges

README.md
This commit fixes the local development guide in README to avoid confusion when contributors set up their local.
(These points are what I noticed while I was preparing for my slides for my JSR meetup talk)
=> docs(readme): fix local development guide

frontend/routes/package/(_components)/PackageHeader.tsx
BEFORE
AFTER
Fixes #489
Fixes #488
=> fix: better warning when a package is yanked or pre-release

api/src/npm/mod.rs, api/src/npm/specifiers.rs, api/src/npm/tarball.rs, api/testdata/specs/npm_tarballs/additional_files.txt, api/testdata/specs/npm_tarballs/import_jsr.txt, api/testdata/specs/npm_tarballs/import_npm.txt, api/testdata/specs/npm_tarballs/jsdoc_import.txt, api/testdata/specs/npm_tarballs/slow_types_transpile.txt, api/testdata/specs/npm_tarballs/transpile.txt, api/testdata/specs/npm_tarballs/transpile_with_imports.txt, api/testdata/specs/npm_tarballs/ts_importing_js_dts.txt, api/testdata/specs/npm_tarballs/type_imports.txt
Some relative specifiers were being incorrectly emitted when referencing a `.js`
file from a `.d.ts` file in the dist folder.
Additionally, `.js` files were previously emitted into a `_dist` folder, which
broke users that need to relatively access files in the NPM package using
`import.meta.url` or similar. Now only `.d.ts` files are emitted into the
`_dist` folder.
Fixes #491
Fixes #477
=> fix: improve npm tarball emit

frontend/routes/badges/package.ts, frontend/routes/badges/package_score.ts, frontend/routes/badges/scope.ts
The JSR logo has been added to Simple Icons since https://github.com/simple-icons/simple-icons/pull/10794.
I used the `logoSize` parameter to make the logo fit the badge. The feature was introduced at https://github.com/badges/shields/pull/9191.
Currently, we can't use `logoSize` in the response due to https://github.com/badges/shields/pull/10132. So I passed these parameters with search parameters instead.
=> refactor: use shields.io built-in JSR logo for badges

frontend/static/styles.css
First attempt at updating some of the styles on the symbol detail pages. I tried to leave some comments on bits where the thing I was changing could actually be fixed by applying a different tailwind class in deno_doc (like changing margin-top when I really want a `space-y-3` to be a `space-y-2`
Same caveat as the last one, this could be used as a TODO list for changes that should happen back in deno_doc or merged in and used as a reference for refactoring later.
Example page of these styles on Oak/oak since that contains a large amount of varied text to format. (sidebar omitted from screenshot since that's changing in a different PR and I didn't want it to distract)
=> fix: update styles on symbol detail pages

frontend/routes/badges/package.ts, frontend/routes/badges/package_score.ts, frontend/routes/badges/scope.ts
- Add `access-control-allow-origin` header
- Use the search parameter `cacheSeconds` to always follow the `cache-control` from `img.shields.io`
=> chore: adjust badge headers

frontend/islands/new.tsx, frontend/routes/new.tsx, frontend/static/styles.css
Note how the "or create a new scope" text is gone, and how you can no longer edit the text fields.
Fixes #478
=> fix: disallow editing on the new page when coming from CLI

frontend/routes/index.tsx, frontend/static/styles.css
Closes https://github.com/jsr-io/jsr/issues/473
Also includes some CSS auto-formatting, and the removal of a wayward server-side `console.log` that somehow made it to prod.
=> Fix: allow module breadcrumbs to wrap on mobile

frontend/docs/with/vite.md
The default port of vite server is `5173`[^1]
[^1]: https://vitejs.dev/config/server-options#server-port
=> docs: fix the default vite port (`5123` -> `5173`)

frontend/docs/about-slow-types.md
=> docs: add section about isolated declarations

frontend/routes/package/(_components)/Docs.tsx, frontend/routes/package/(_components)/PackageHeader.tsx, frontend/routes/package/(_components)/PackageNav.tsx, frontend/routes/package/(_islands)/BreadcrumbsSticky.tsx, frontend/routes/package/(_islands)/LocalSymbolSearch.tsx, frontend/static/styles.css
A few different updates here:
1. The "use with" button was a little too blue and didn't offer enough contrast from the text and logos, it now matches the style we use for the package navigation. 
2. The symbol search box has matching styles to the code sample boxes
3. The width of this section was increased by raising going from a 75/25 layout to 70/30, giving a bit more space to show longer text in document navigation and the import symbol code snippet
4. Symbol search is the same width in all instances 
This proposes moving the version counter out of the package navigation and making note of the most recently published version in the package metadata section where we mention when a package was last published. This cleans up the UI a bit to prevent badge overload (there are already up to …
=> fix: update layout and breadcrumb/nav styles

e2e/main_test.ts, frontend/routes/badges/package.ts, frontend/routes/badges/package_score.ts, frontend/routes/badges/scope.ts
We passed an incorrect url to shields.io for generating the badges. 
This regression was introduced in https://github.com/jsr-io/jsr/pull/510/files#diff-8caf5f85764d74fed531a1043245722b7f0fb15b3354df1ff3468742cd450ed7L35
Fixes https://github.com/jsr-io/jsr/issues/539
=> fix: broken badge urls

frontend/routes/package/(_components)/Docs.tsx
The usage box will now remember what package manager the user last selected for the next page load / session.
This data is stored on device, and thus does not sync between devices.
Closes #546
=> fix: remember the users package manager preference

frontend/routes/package/(_components)/Docs.tsx
This fixes a bug that occurred in #548.
If you select Bun in a package(e.g. https://jsr.io/@std/assert) and move to another package(e.g. https://jsr.io/@std/archive) where Bun does not work, the package manager will not display correctly.
=> fix: display the default package manager

frontend/components/Header.tsx, frontend/components/Modal.tsx, frontend/components/RuntimeCompatIndicator.tsx, frontend/components/Tooltip.tsx, frontend/components/icons/Check.tsx, frontend/components/icons/CheckmarkStamp.tsx, frontend/components/icons/ChevronRight.tsx, frontend/components/icons/Cross.tsx, frontend/components/icons/Error.tsx, frontend/components/icons/Folder.tsx, frontend/components/icons/GitHub.tsx, frontend/components/icons/Plus.tsx, frontend/components/icons/Source.tsx, frontend/islands/GlobalSearch.tsx, frontend/islands/HomepageHeroParticles.tsx, frontend/routes/_layout.tsx, frontend/routes/account/tokens/(_islands)/RevokeToken.tsx, frontend/routes/account/tokens/index.tsx, frontend/routes/index.tsx, frontend/routes/package/(_components)/PackageHeader.tsx, frontend/routes/package/(_islands)/LocalSymbolSearch.tsx, frontend/routes/package/publish.tsx, frontend/routes/package/score.tsx, frontend/routes/package/versions.tsx, frontend/routes/packages.tsx, frontend/static/styles.css
This PR includes a bunch of big and small accessibility improvements spread across the whole frontend-part of JSR.
If you have any questions please let me know :)
Here is a list of what I've changed, fixed and improved:
- Removed all alt-text from the logos on the frontpage.
- Since they are purely decoration they only add noise to a screen reader, eg: "Works with any runtime... <paragraph>... Deno logo. Bun logo." etc.
- Moved the timestamp in the footer inside a [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time)-element.
- Replaced the `type="text"` for global and symbol search with `type="search"`.
- Fixed contrasting colors a bunch of different places
- This is the one I'm most uncertain of because I don't know if you are attached to the failing colors, if they …
=> fix(frontend): Big and small accessibility improvements

frontend/routes/package/publish.tsx
In this PR:
- Add missing background on GitHub Workflow .yml example
- The text is currently invisible and makes for a confusing experience
=> fix: Add missing background on GitHub Workflow .yml example

frontend/components/ListPanel.tsx
In this PR:
- Only apply background color to odd `ListPanel` children if there's more than one
- `ListPanel` is used by `[id].tsx` to show which scopes you're a member of. If the user is only a member of one scope, then `ListPanel` will add a background color. This has a side effect of making it look like an input field. I propose we disable coloring the background if there's only a single child.
- Resolves https://github.com/jsr-io/jsr/issues/424
=> feat(#424): Only apply background color to odd `ListPanel` children if there's more than one

frontend/components/RuntimeCompatIndicator.tsx
In this PR:
- Improve `RuntimeCompatIndicator` sorting and accessibility
- Sort unknown runtimes to beginning of list to improve readability at quick glance
- Add `title` and `alt` attributes where applicable to improve accessibility and UX
- If `runtimeCompat` prop is an empty object, then show all runtimes with unknown status instead of rendering empty container, which resolves https://github.com/jsr-io/jsr/issues/443.
=> fix(#443): Improve `RuntimeCompatIndicator` sort and accessibility

e2e/main_test.ts, frontend/docs/badges.md, frontend/routes/badges/package.ts, frontend/routes/badges/package_score.ts, frontend/routes/badges/scope.ts
In this PR:
- Allow specifying `logoColor` when generating badge, fallback to `rgb(8,51,68)` if none is explicitly set, resolves #626
- Update documentation
- Update e2e tests
=> feat(#626): Allow specifying `logoColor` when generating badge

frontend/routes/package/og.ts
I added Content-Type to OGP Image.
When it's in production environment, Content-Type be `text/html` so I fixed it.
=> feat(ogp): Add Content-Type to OGP Image

README.md
I can't find the `_tools/convert_to_workspace.ts` in `deno_std`. I believe it's likely been removed since `deno_std` is now published on jsr under `@std/`?
=> chore: remove deno_std workspace setup from local dev instructions

api/src/api/admin.rs, api/src/api/scope.rs, api/src/api/types.rs, deno.json, docker-compose.yml, frontend/components/URLQuerySearch.tsx, frontend/fresh.gen.ts, frontend/routes/admin/scopes/assign.tsx, frontend/routes/admin/scopes/index.tsx
This alleviates the need for users being assigned
scopes to manually accept an invitation.
=> feat: add an API to assign reserved scopes

.github/workflows/ci.yml, frontend/static/styles.css
A few small things addressed in this PR
- One column symbol layout 
- Link to code snippets visible on hover instead of by default 
- H1 at the top of readme gets a special style treatment
- Fixed some bugs with mobile viewport rendering of the usage block
https://jam.dev/c/6a322747-f14b-4f3e-be9d-2b81669ff8d0
=> Small style updates and UI fixes (including one-col symbol layout)

frontend/docs/badges.md
This polishes the example badge to give it a better visual.
I also added the `message` to the ignore list.
=> docs: polish custom badge example

frontend/static/styles.css
From #675, code copy button is no longer displayed when hovered. This PR fixes it.
=> fix: display code copy button on hover

api/src/docs.rs
Fix JSX `draggable={false}` incorrectly used as HTML `draggable="false"`.
=> fix: correctly mark logos on docs page as undraggable

frontend/routes/package/(_components)/PackageHeader.tsx
If you try to access this package via the following URL: 
https://jsr.io/@planetarium/lib9c@0.3.0-dev.202409100854550774+2db5208d2bf73ba22624cdd8f2f7cf167097359e
you'll notice that the right side of the package header isn’t fully visible. This happens because the version string is unusually long.
While this issue is rare, I wanted to ensure that the package details are at least viewable. I considered implementing a more polished solution, but it impacted other parts of the UI and required more effort for something that doesn't occur often. So, I decided to go with a simpler, cleaner fix that achieves the primary goal which is making the information visible.
so now it looks like this:
=> fix: make the right side of package header visible

frontend/docs/about-slow-types.md
"it's" means "it is", and is not a possessive.
=> docs: fix typo

api/src/api/package.rs, api/src/db/models.rs, api/src/docs.rs
For https://github.com/jsr-io/jsr/issues/717
> We could do a fallback mechanism though: either we link to JSR source if the file exists, or to GitHub if that is specified, or it is a dead link.
_Originally posted by @lucacasonato in https://github.com/jsr-io/jsr/issues/717#issuecomment-2343859084_
=> fix: make links relative to github for readme if github repo is present

frontend/static/logo.svg
I saw [this post](https://deno.com/blog/designing-jsr) on social media and decided to check the SVG code of the logo, and I noticed it could be made smaller by manually tweaking the coordinates of the paths, so we get this for the background:
```diff
- M0,2h2v-2h7v1h4v4h-2v2h-7v-1h-4
+ M0 6h4v1h7V5h2V1H9V0H2v2H0
```
And this for the foreground:
```diff
- M1,3h1v1h1v-3h1v4h-3M5,1h3v1h-2v1h2v3h-3v-1h2v-1h-2M9,2h3v2h-1v-1h-1v3h-1
+ M4 5V1H3v3H2V3H1v2h6V4H5V1h3v1h4v2h-1V3h-1v3H9V2H6v1h2v3H5V5
```
It's a tiny improvement (18 less bytes), so feel free to reject this PR. I did the same thing in the past with the [NPM Logo](https://gist.github.com/loucyx/73a3b2a2db9d9b629a94) ... I just love to optimize SVGs manually 😅
=> chore: optimized SVG logo

frontend/docs/package-configuration.md
Current link isn't valid, I'm guessing this was the intended target.
=> fix(docs): fixes href for "Learn more about scope and package names"

frontend/docs/migrate-x-to-jsr.md
i wasn't able to find code diff example for the third "vendoring dependencies" section, so i'm open to suggestions there
=> update docs about migrating from HTTP specifiers

frontend/routes/package/(_islands)/LocalSymbolSearch.tsx
closes https://github.com/jsr-io/jsr/issues/775.
this extends the local symbol search by generating more tokens for the `name` prop, thus improving the overall search ux.
the output for `tokenize` is changed from this:
```ts
["assert", "almost", "equals", "assertalmostequals"]
```
to this:
```ts
["assert", "almost", "equals", "assertalmost", "almostequals" ,"assertalmostequals"]
```
=> fix(docs): more flexible local symbol search

frontend/routes/package/score.tsx
closes https://github.com/jsr-io/jsr/issues/748.
as already expected in the issue there was some rounding happening, caused by `.toFixed(0)`:
changes the implementation to make use of `Math.floor`.
=> fix(frontend): displayed percentage of documented symbols

README.md
closes https://github.com/jsr-io/jsr/issues/816.
=> chore: update readme on how to populate local dev environment

frontend/routes/_app.tsx, frontend/static/opensearch.xml
Closes #457 
When we open the site in Firefox's search field, we can see that new suggestions appear.
=> feat: support for OpenSearch

frontend/routes/package/publish.tsx
This PR add the `license` field to the `config file` example in **How to publish** page.
Closes #764
=> fix(frontend): add license field to example config file

api/src/tree_sitter.rs, frontend/static/styles.css
Fixes #31 
The width of the line highlight takes up the entire content
=> fix(frontend): fix up line highlight width in source view

Cargo.lock, api/Cargo.toml, api/src/docs.rs, api/src/docs/bulb.svg, api/src/docs/info-circle.svg, api/src/docs/warning-message.svg, api/src/docs/warning-octagon.svg, api/src/docs/warning-triangle.svg, frontend/deno.lock
See https://github.com/denoland/deno_doc/pull/665
=> refactor: move ammonia and additional comrak features over from deno_doc

frontend/static/styles.css
This closes #866, see issue for video of original issue. Resolves the shift caused by mismatch in the SVG and text heights.
https://github.com/user-attachments/assets/1b533313-60bc-4637-97d9-f0b51c4f4106
=> fix: prevent layout shift when hovering over doc header

api/src/npm/tarball.rs, api/src/publish.rs, api/src/tarball.rs, frontend/static/schema/config-file.v1.json
https://github.com/dsherret/jsr-publish-on-tag/actions/runs/12332179143/job/34419677355
```
$ deno publish --set-version 0.2.0
Download https://registry.npmjs.org/@types/node/-/node-18.16.19.tgz
Check file:///home/runner/work/jsr-publish-on-tag/jsr-publish-on-tag/src/main.ts
Checking for slow types in the public API...
Check file:///home/runner/work/jsr-publish-on-tag/jsr-publish-on-tag/src/main.ts
Publishing @david/publish-on-tag@0.2.0 ...
error: Failed to publish @david/publish-on-tag@0.2.0
Caused by:
Failed to publish @david/publish-on-tag at 0.2.0: invalid config file '/deno.json': missing field `version`
Error: Process completed with exit code 1.
```
=> fix: allow publishing with no version in config file

frontend/routes/package/og.ts
closes #801
> [!NOTE]
> The header name uses lowercase because the other `access-control-allow-origin` uses also lowercase.
> https://github.com/search?q=repo%3Ajsr-io%2Fjsr%20access-control-allow-origin&type=code
=> feat: allow cross-origin use of og images

frontend/routes/package/settings.tsx
=> fix: Package runtime compat is now shown properly

frontend/islands/GlobalSearch.tsx, frontend/utils/os.ts
When a user opens [jsr.io](https://jsr.io), the page shows a big input element which is used to search for packages. It appears to be the primary call to action element and I believe by default, it should be focused on page load because most of the times, a user would visit jsr to search for a package.
This behaviour would also align with [google.com](https://google.com)
=> feat: focus search input on page load

frontend/islands/GithubUserLink.tsx, frontend/utils/github.ts
=> fix: Refetch username after delay when github api rate limit is triggered

frontend/routes/package/score.tsx
Fixes #902
fixes quote escaping by wrapping `"compatible"` as `<span>"compatible"</span>`
=> fix: unescape quotes (#902)

frontend/docs/about-slow-types.md
fixes the mistyped spelling of "function"
=> docs: funtion ▶︎ function

frontend/components/Nav.tsx, frontend/islands/UserMenu.tsx
**Before**
**After**
Fixe #926
=> fix(UI): better focus

frontend/routes/package/(_islands)/DependencyGraph.tsx
=> fix(UI): improve dependency graph node rendering

api/src/docs.rs
Trying to get the "Expression" link at https://jsr.io/@babel-test-6ae45912/parser@0.0.7-8.0.0-alpha.15/doc/~/parseExpression to work:
- it's missing the `/doc` in the URL
- if the type is imported from a non-default entrypoint, it should link to it
- if it's imported from a specific version, it should link to that version (this makes it work with pre-releases)
=> Fix cross-package links in docs

frontend/routes/_layout.tsx, frontend/static/styles.css
In the first three `calc()` expressions, `100vw` is less than `1280px` (otherwise we'd be in the `screen(xl)` media query), so `min(1280px, 100vw)` is just a complex way to say `100vw`, and thus `calc((100vw - (min(1280px, 100vw) - 32px)) / 2 * -1)` is just a very complex way to say `-16px`. I simplified them to the corresponding `-mx-` classes, so that it's clear that they are the same numbers used in `.section-x-inset-xl`.
In the last `calc()`, `100vw` is always more than `1280px` (because of the media query), so `min(1280px, 100vw)` is just a complex way of saying `1280px`. I left `1280px - 112px` which is hopefully more clear than just writing `1068px`.
Note that using `100vw` instead of `1280px` in the last one would fix the bug reported in https://github.com/jsr-io/jsr/issues/944, …
=> Simplify `.-section-x-inset-xl` CSS

frontend/routes/_layout.tsx
Fixes https://github.com/jsr-io/jsr/pull/945#issuecomment-2647716883. 
Only tested by changing the value in the browser devtools.
=> Mark the page wrapper as a container only in the inline direction and not block

frontend/docs/publishing-packages.md
Fixes #797 
Took as a reference the [deno documentation](https://docs.deno.com/runtime/fundamentals/configuration/#include-and-exclude)
=> docs: updated Deno subcommands in publishing documentation

frontend/islands/new.tsx
Fixes #960
Even with other error messages
=> fix(ui): Drop shadow overlaped error text, now it doesn't

frontend/components/NavOverflow.tsx, frontend/deno.json, frontend/islands/UserMenu.tsx, frontend/routes/admin/scopes/index.tsx, frontend/routes/new.tsx
Removes deprecated $tabler_icons import and replaces specific Tabler icons with equivalent icons from @preact-icons/tb across multiple components and routes. Part of the icons migration proposed in #931
=> refactor: replace $tabler_icons with @preact-icons/tb icons

frontend/islands/GithubUserLink.tsx, frontend/routes/account/(_components)/AccountLayout.tsx
- add GH icon
- give space between account info and link. because in future if there are more link it's will be interesting to have such as small section 
- change ring color of avatar to fit with the ring in header
=> feat(acout page): refine

frontend/islands/GlobalSearch.tsx
=> fix(ui): trunck instead of overflow in search box

api/.sqlx/query-8433bacb42d0833b723781eff2467ab27542e94691c1a5626c3f3d8c090caa54.json, api/src/api/package.rs, api/src/api/types.rs, api/src/db/database.rs, frontend/routes/package/(_components)/PackageNav.tsx, frontend/routes/package/all_symbols.tsx, frontend/routes/package/dependencies/graph.tsx, frontend/routes/package/dependencies/index.tsx, frontend/routes/package/dependents.tsx, frontend/routes/package/doc/[file].tsx, frontend/routes/package/doc/[symbol].tsx, frontend/routes/package/index.tsx, frontend/routes/package/publish.tsx, frontend/routes/package/score.tsx, frontend/routes/package/settings.tsx, frontend/routes/package/source.tsx, frontend/routes/package/versions.tsx, frontend/routes/status.tsx, frontend/utils/api_types.ts, frontend/utils/data.ts
Fixes https://github.com/jsr-io/jsr/issues/342.
I think a should export some code to improve visibility in of the `get_handler` function in `package.rs` into an other file but where ? `utils.rs` ?
Ready to read suggestions and make changes if needed !
=> feat : Show dependencies dependents count #342

frontend/routes/package/(_components)/PackageHeader.tsx
#925 
Adding button to report malware.
Desktop: 
Mobile:
=> feat: add report package button

frontend/deno.json, frontend/deno.lock, frontend/routes/package/source.tsx
=> refactor: Usage of @std/fmt instead of manual size calculation

frontend/routes/package/(_islands)/DependencyGraph.tsx
=> refactor: replaced custom byte size calculation with @std/fmt

frontend/routes/package/(_components)/PackageHeader.tsx
Fullscreen view (almost) unchanged
Button was oversized on smaller screen
Before :
After :
=> fix: unifed size for report package button

frontend/components/QuotaCard.tsx
=> feat(UI): have red ring when full quotas

api/src/api.yml
=> fix: add nullable:true to rekorLogId

frontend/deno.lock, frontend/routes/package/(_islands)/DownloadChart.tsx, frontend/routes/package/(_islands)/DownloadWidget.tsx
This PR fixes the rendering of download chart when the recent 5 versions don't have enough x values in the chart.
This PR fixes the download chart of `@ecopages/lit` package:
BEFORE
AFTER
=> fix(frontend): fix data point aggregation logic for download chart

frontend/islands/DarkModeToggle.tsx
Thanks for shipping Dark mode for JSR! (#1055) 🎉 
Though I noticed that the media `prefers-color-scheme` detection is not working correctly. During loading the correct theme will be applied (via `_app.tsx` script), but when Preact renders it will override with incorrect theme. This is because the `isDarkStored ?? isDarkPreference` expression basically always returning `isDarkStored` (`isDarkStored` is `boolean`, not `boolean | undefined | null`).
This PR attempts to fix the issue by ensuring the [logic is the same as for `_app.tsx`](https://github.com/jsr-io/jsr/blob/main/frontend/routes/_app.tsx#L74-L81) for when Dark mode should be applied, which avoids dark -> light flashing for when dark mode is preferred without any stored value.
This is how it looks for me (3G throttled) when I have …
=> fix: correct default dark-mode preference

frontend/routes/package/(_islands)/DownloadChart.tsx, frontend/routes/package/versions.tsx
=> fix(frontend): legend overlapping dropdown on small breakpoints

frontend/docs/publishing-packages.md
When [publishing from GitHub Actions](https://jsr.io/docs/publishing-packages#publishing-from-github-actions), `deno.json(c)` is used if `jsr.json` doesn't exist.
=> docs: mention deno.json(c) in publishing from GitHub

frontend/routes/new.tsx
Fixes the dark mode colors for the "You must be logged in" box.
I also added a border color in case that is ever used/wanted.
Before: 
After:
=> fix: dark mode colors on /new page

frontend/islands/DarkModeToggle.tsx, frontend/islands/PublishingTaskRequeue.tsx, frontend/islands/TicketMessageInput.tsx, frontend/islands/TicketModal.tsx, frontend/islands/UserMenu.tsx, frontend/routes/admin/(_islands)/EditModal.tsx, frontend/routes/package/(_islands)/DownloadChart.tsx, frontend/routes/package/(_islands)/DownloadWidget.tsx
`useSignal()` is more ergonomic and performant than `useState()`.
=> refactor(frontend): use Preact Signals

frontend/static/styles.css
Fixes #1115 
<br/>And if changing dababase queries, be sure you have ran `sqlx prepare`
and committed the changes in the `.sqlx` directory.
([Safari does not support this](https://bugs.webkit.org/show_bug.cgi?id=199134), you need to use Chrome or Firefox to reproduce this issue)
1. Switch to dark mode
1. Modify any img src to `https://cdn.simpleicons.org/jsr/yellow/blue` in your inspector 
1. The image color should be blue, but it's yellow on production
The package readme may include a dynamic color scheme style in the image, like this project's readme: …
=> fix: specify the color-scheme for dark mode

frontend/static/schema/config-file.v1.json
License field or license file has required but JSON schema of jsr.json doesn't has a field of this. So I added it.
<br/>And if changing dababase queries, be sure you have ran `sqlx prepare`
and committed the changes in the `.sqlx` directory.
=> fix(schema): add license field

frontend/islands/GlobalSearch.tsx
Fixes: #819 
<details>
<summary>Before (Click to open)</summary>
</details>
<details>
<summary>After (Click to open)</summary>
</details>
=> fix: selection highlight is offset in global search

api/src/metadata.rs
=> feat: add createdAt field to package metadata
