frontend/routes/package/score.tsx
Add alt text to the logo displayed on the package page.
=> fix: add alt text to img

frontend/components/Header.tsx, frontend/components/Nav.tsx, frontend/routes/index.tsx, frontend/static/styles.css
- Removed selectability on buttons and logo images.
- Removed unused space between nav items.
- Made logo images non-draggable.
=> Minor UI improvements

frontend/routes/_layout.tsx
Closes https://github.com/jsr-io/jsr/pull/124
=> feat: add link to the github repo in  the footer

frontend/islands/HomepageHero.tsx
As reported in https://github.com/jsr-io/jsr/pull/103
This is the same fix, but applied in a more targeted way to avoid any possible side effects.
=> Fix horizontal scroll on homepage

api/src/ids.rs
Fixes https://github.com/jsr-io/jsr/issues/143
This PR improves recognition of readme files according to the discussion in https://github.com/jsr-io/jsr/issues/143.
=> fix: improved recognition of readme files

api/src/ids.rs, frontend/docs/publishing-packages.md, frontend/islands/new.tsx
=> fix: allow package names up to 32 chars long

frontend/docs/publishing-packages.md
=> docs: ignoring files is broken

frontend/docs/scoring.md
=> fix: typo of wheights

frontend/routes/package/versions.tsx
=> fix: dont use prerelease in releasetrack

api/src/analysis.rs, api/src/publish.rs, api/testdata/tarballs/dynamic_import/jsr.json, api/testdata/tarballs/dynamic_import/mod.ts
=> fix: correctly analyze packages in dynamic imports

api/src/analysis.rs, api/src/npm/mod.rs, api/src/npm/tarball.rs, api/src/npm/types.rs
Reincarnation of #56
Co-authored-by: Marvin Hagemeister <marvin@deno.com>
=> fix: include other non-graph files in NPM tarball

api/src/api/admin.rs, api/src/api/package.rs, api/src/publish.rs
When a new version is published, or provenance is added, we need to update orama so it reflects the new score.
Fixes https://github.com/jsr-io/jsr/issues/193
=> fix: update orama index on score changes

Cargo.lock, api/Cargo.toml, api/src/api/package.rs, api/src/api/types.rs, api/src/docs.rs, frontend/routes/package/(_components)/Docs.tsx, frontend/static/styles.css, frontend/util.ts, frontend/utils/api_types.ts, frontend/utils/data.ts
Closes #126 
Closes #128
Closes #153
Closes #158
Closes #75
Closes #89
Closes #90
Closes #106
Closes #197
Closes #125
Closes #43
Closes #241
=> chore: update deno_doc

frontend/static/styles.css
=> fix: incorrect code block styling

frontend/static/styles.css
The current table design seems to be default design.
I add table styles to match other designs.
Before
After
https://jsr.io/@ryu/enogu
=> chore: add table design

api/src/api/package.rs
Fixes #262
@crowlKats can you upstream?
=> fix: walk up node tree for copy button

terraform/https.tf
I broke everything in my last PR (reverted now).
=> fix: punch through googlebot without breaking everything

frontend/islands/PackageSearch.tsx
Fixes https://github.com/jsr-io/jsr/issues/307
=> fix: wrong key combo shown in package search

Cargo.lock, api/Cargo.toml, api/src/api/package.rs, api/src/api/types.rs, api/src/docs.rs, frontend/routes/package/doc/[file].tsx, frontend/routes/package/doc/[symbol].tsx, frontend/routes/package/index.tsx, frontend/routes/package/symbols.tsx, frontend/utils/api.ts, frontend/utils/api_types.ts, frontend/utils/data.ts, tools/orama_package_reindex.ts
=> feat: update deno_doc & support drilldown

frontend/routes/package/(_components)/Docs.tsx
=> fix: symbol search results overflow ontop

frontend/routes/docs/[...id].tsx, frontend/routes/package/(_components)/PackageHeader.tsx, frontend/routes/package/publish.tsx
It is a good practice to open external links in new tabs.
=> fix: open external links in new tabs

frontend/docs/faq.md
=> docs: add FAQ for meaning of JSR

frontend/islands/new.tsx
=> fix: don't show Not Found error when package name includes /

Cargo.lock, api/Cargo.toml, api/src/analysis.rs, api/src/metadata.rs, api/src/npm/emit.rs, api/src/npm/tarball.rs, api/src/publish.rs, api/src/tarball.rs, api/testdata/tarballs/module_graph/jsr.d.ts, api/testdata/tarballs/module_graph/jsr.json, api/testdata/tarballs/module_graph/mod.tsx, api/testdata/tarballs/module_graph/test.d.ts, api/testdata/tarballs/module_graph/test.js, frontend/docs/api.md
Moves from moduleGraph1 to moduleGraph2.
=> chore: upgrade deno_graph 0.74.1

frontend/routes/package/(_components)/Docs.tsx, frontend/static/styles.css
=> fix: show search and usage on mobile

api/src/docs.rs
=> fix: don't unwrap on url parsing for location.filename

frontend/routes/docs/[...id].tsx
=> fix: make docs page work on windows

frontend/docs/about-slow-types.md
=> docs: explain how to ignore slow types

api/src/api/errors.rs, api/src/api/package.rs, api/src/publish.rs, api/testdata/tarballs/ok/mod.ts
=> fix: support non-ascii symbols

Cargo.lock, api/Cargo.toml, frontend/routes/package/(_islands)/LocalSymbolSearch.tsx, frontend/static/styles.css
also contains fixes for mobile overflow
=> chore: upstream styling to deno_doc

frontend/routes/package/(_components)/PackageHeader.tsx
=> feat: clickable package name

frontend/routes/package/(_components)/Docs.tsx, frontend/routes/package/(_islands)/BreadcrumbsSticky.tsx, frontend/routes/package/(_islands)/LocalSymbolSearch.tsx, frontend/static/styles.css
=> fix: excessive scroll bars on sidebar

api/src/api/package.rs, api/src/orama.rs, frontend/routes/packages.tsx, tools/orama_package_reindex.ts
=> fix: exclude packages with no published versions from search

api/src/publish.rs, api/src/tarball.rs
=> chore: unify error code for missingConstraint

api/src/api/package.rs, frontend/routes/package/(_components)/Docs.tsx, frontend/routes/package/(_islands)/BreadcrumbsSticky.tsx, frontend/routes/package/(_islands)/LocalSymbolSearch.tsx, frontend/static/styles.css
This commit adds support for full screen symbol
search with highlighting of the search results.
Closes #16
=> feat: fullscreen symbol search

api/src/api.yml
Upstreaming changes from [jsr_ios/openapi.yaml](https://github.com/littledivy/jsr_ios/blob/main/JSR/openapi.yaml)
- Add `?query=<string>` to `/packages`
- Add `/scopes/{scope}/packages/{package}/score` and `PackageScore`
- Add `score` property to `Package`
- Fix `PackageVersion` name -> package
- Add `rekorLogId` to `PackageVersion`
- Add `featured` to `Stats`
- ~~Add `/scopes/{scope}/packages/{package}/versions/{version}/docs` and `PackageDocs`~~
=> Update openapi spec

api/src/api/package.rs, api/src/db/models.rs, api/src/npm/specifiers.rs, api/src/npm/tarball.rs, api/src/util.rs, rust-toolchain.toml
- **upgrade rust to 1.79.0**
- **clippy**
=> chore: upgrade rust to 1.79.0

terraform/https.tf
=> fix: allow various crawlers for OG data scraping

Cargo.lock, api/Cargo.toml, api/src/analysis.rs, api/src/api/package.rs, api/src/docs.rs, api/src/npm/emit.rs, api/src/npm/tarball.rs, api/testdata/specs/npm_tarballs/import_jsr.txt, api/testdata/specs/npm_tarballs/import_npm.txt, api/testdata/specs/npm_tarballs/jsdoc_import.txt
* https://github.com/denoland/deno_doc/pull/611
* https://github.com/denoland/deno_doc/pull/605
=> fix: update deno_doc and other deno crates

terraform/buckets.tf, terraform/cloud_run_api.tf, terraform/https.tf
=> feat: add cors to API endpoints

api/src/analysis.rs, api/src/docs.rs, api/src/publish.rs, api/src/tarball.rs, api/testdata/tarballs/bun_import/jsr.json, api/testdata/tarballs/bun_import/mod.ts, frontend/docs/troubleshooting.md
=> feat: allow `bun:` specifiers in published packages

frontend/docs/go.ts, frontend/docs/troubleshooting.md
=> docs: add entry for missingLicense

api/src/api/package.rs, api/src/provenance.rs
Deno PR: https://github.com/denoland/deno/pull/25200
=> fix: allow slsa spec compliant subjects in provenance

.github/workflows/ci.yml, .github/workflows/orama_package_reindex.yml, frontend/Dockerfile, frontend/deno.json, frontend/islands/Authorize.tsx, frontend/islands/GlobalSearch.tsx, frontend/islands/HomepageHeroParticles.tsx, frontend/routes/package/publish.tsx, frontend/routes/package/score.tsx, frontend/utils/os.ts
- **fix: mention deno publish in GHA linking docs**
- **fix: improve wording on docs part of JSR score**
See https://github.com/jsr-io/jsr/issues/717
=> fix: various improvements for the website

.github/workflows/ci.yml, .github/workflows/orama_symbols_reindex.yml, Cargo.lock, api/Cargo.toml, api/src/analysis.rs, api/src/api/package.rs, api/src/config.rs, api/src/docs.rs, api/src/main.rs, api/src/orama.rs, api/src/publish.rs, api/src/tarball.rs, deno.json, terraform/cloud_run_api.tf, terraform/scheduler.tf, terraform/secrets.tf, terraform/variables.tf, tools/orama_symbols_reindex.ts
search itself will be added next week
=> feat: add symbols to orama

frontend/routes/package/dependencies.tsx
closes https://github.com/jsr-io/jsr/issues/711.
=> fix(frontend): let `npm:@jsr/scope__package` dependency links link to `jsr`

api/src/orama.rs, tools/orama_package_reindex.ts
Will require a reindex afterwards
=> fix(orama): use _omc:number instead of _omc

README.md
Closes #822
See https://github.com/denoland/deno_doc/pull/672
=> docs: add information on contributing to the documentation generation

frontend/docs/about-slow-types.md, frontend/docs/faq.md, frontend/docs/npm-compatibility.md, frontend/docs/packages.md, frontend/docs/private-registries.md, frontend/docs/scopes.md
=> Docs: “can not” ▶︎ “cannot”

frontend/routes/package/publish.tsx
=> fix: Fixed broken anchor, to target to an already existing and related topic in the docs

frontend/routes/_layout.tsx
In future text link of social network can be replaced by icons
=> feat(ui): add social link

frontend/islands/new.tsx
fix #900 + giving little bit more space between text and button because shadow of the button was to close to the text.
=> feat(ui): add scope naming policy link

frontend/routes/_error.tsx
Adding link to home when it's 404 error.
=> feat(ui): polish error page when 404

frontend/routes/docs/[...id].tsx
=> ui(doc): add github icon

frontend/components/Nav.tsx
=> UI: prevent jumping on NavItem

frontend/islands/TicketMessageInput.tsx
**Min height**:
**Adding icon**:
=> feat(admin): add icon + min height

frontend/routes/account/(_components)/AccountLayout.tsx
=> fix(user): trunck when long username

frontend/routes/admin/(_components)/URLQuerySearch.tsx, frontend/routes/admin/publishingTasks.tsx, frontend/routes/admin/scopes/index.tsx, frontend/routes/admin/tickets.tsx
- add color to differentiate error/success
- remove layout shift when there are unread notifications
=> fix(admin): align notifcation on ticket list, wrap assign scope button, make failure case of tasks red

frontend/islands/new.tsx
<details>
<summary>Before (Click to open)</summary>
</details>
<details>
<summary>After (Click to open)</summary>
</details>
=> fix: bg on select dropdown

api/src/db/models.rs, frontend/routes/package/score.tsx
part of #1104
<br/>And if changing dababase queries, be sure you have ran `sqlx prepare`
and committed the changes in the `.sqlx` directory.
=> feat(ui): Better incation score

Cargo.lock, api/Cargo.toml, api/src/analysis.rs, api/src/api/package.rs, api/src/npm/tarball.rs, api/src/publish.rs
<br/>And if changing dababase queries, be sure you have ran `sqlx prepare`
and committed the changes in the `.sqlx` directory.
=> refactor: update to deno_graph 0.97
